Add linux-install-jj

diff --git a/brainsik/bin/linux-install-ghrepo-release-binary b/brainsik/bin/linux-install-ghrepo-release-binary
--- a/brainsik/bin/linux-install-ghrepo-release-binary
+++ b/brainsik/bin/linux-install-ghrepo-release-binary
@@ -23,7 +23,17 @@ url="https://github.com/$repo/releases/download/$tag/$name-$tag-$arch-unknown-li
 curl -fL --progress-bar --output "$file" "$url"
 
 tar -xzof "$file" -C "$tmpdir"
-mv "$tmpdir/$name-$tag-$arch-unknown-linux-$libc/$name" "$HOME/bin/$name"
+
+if [[ -s "$tmpdir/$name-$tag-$arch-unknown-linux-$libc/$name" ]]; then
+    binpath="$tmpdir/$name-$tag-$arch-unknown-linux-$libc/$name"
+elif [[ -s "$tmpdir/$name" ]]; then
+    binpath="$tmpdir/$name"
+else
+    echo "💥 Couldn't find binary in $tmpdir:"
+    ls -oh "$tmpdir"
+    exit 1
+fi
+mv "$binpath" "$HOME/bin/$name"
 rm -rf "$tmpdir"
 
 "$HOME/bin/$name" --version
